# Generated by Django 4.1 on 2022-10-14 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video_editor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.CharField(max_length=256)),
                ('count_hashtag', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('top_hashtag', models.BooleanField(default=False)),
                ('count_top_tag_list', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VideoOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Owner_id', models.BigIntegerField()),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('total_videos', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('upated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_editor.videoowner', verbose_name='Video Onwer')),
                ('video_hashtags', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_editor.hashtag', verbose_name='Video tags')),
            ],
        ),
    ]
