# Generated by Django 4.1 on 2022-10-14 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_editor', '0002_hashtag_videoowner_videoid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hashtag',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='videoid',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='videoowner',
            old_name='upated_at',
            new_name='updated_at',
        ),
    ]
