# Generated by Django 4.1 on 2022-10-14 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_editor', '0003_rename_update_at_hashtag_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videoowner',
            old_name='Owner_id',
            new_name='owner_id',
        ),
    ]
