# Generated by Django 4.1 on 2022-10-16 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_editor', '0004_rename_owner_id_videoowner_owner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='count_hashtag',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='count_top_tag_list',
            field=models.IntegerField(default=0),
        ),
    ]
