# Generated by Django 4.1 on 2022-10-16 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_editor', '0005_alter_hashtag_count_hashtag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='hashtag',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='videoid',
            name='video_id',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='videoowner',
            name='owner_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
