# Generated by Django 4.1 on 2022-10-16 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_editor', '0006_alter_hashtag_hashtag_alter_videoid_video_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='count_hashtag',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
