# Generated by Django 4.1 on 2022-10-16 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_editor', '0007_alter_hashtag_count_hashtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='count_top_tag_list',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='top_hashtag',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
