# Generated by Django 4.1 on 2022-10-20 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_editor', '0009_videoid_len_hashtags_videoowner_instagram_acc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoowner',
            name='count_videos',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
