# Generated by Django 4.1 on 2022-10-21 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video_editor', '0010_videoowner_count_videos'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('instagram_acc', models.CharField(blank=True, max_length=100, null=True)),
                ('total_videos', models.IntegerField(blank=True, null=True)),
                ('count_videos', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='videoid',
            name='owner_id',
        ),
        migrations.DeleteModel(
            name='VideoOwner',
        ),
        migrations.AddField(
            model_name='videoid',
            name='author_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='video_editor.videoauthor', verbose_name='Video Onwer'),
        ),
    ]
