# Generated by Django 4.1 on 2022-10-21 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video_editor', '0011_videoauthor_remove_videoid_owner_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoid',
            name='author_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='video_editor.videoauthor', verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='videoid',
            name='video_hashtags',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Video tags'),
        ),
    ]
