# Generated by Django 4.1 on 2022-10-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_editor', '0013_alter_videoid_video_hashtags'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoauthor',
            name='followers',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
